version: '3'
services:
    postgres:
        image: postgres
        restart: always
        # Uncomment the next two lines to connect to your your database from outside the Docker environment, e.g. using a database GUI like Postico
        ports:
            - '5432:5432'
        environment:
            POSTGRES_USER: prisma
            POSTGRES_PASSWORD: prisma
        volumes:
            - postgres:/var/lib/postgresql/data
volumes:
    postgres:
